client_config_backend: settings
client_config:
  client_id: 177974848834-uiv5nbe0avrg0cp15la0f29u051u2vob.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.metadata.readonly
  - https://www.googleapis.com/auth/drive.appdata
  - https://www.googleapis.com/auth/drive.install